import { AppError } from "@/common/errors/app-error"
import { HTTP_STATUS } from "@/common/constants/http.constants"
import { Station } from "../../domain/entities/Station"
import { IStationRepository } from "../../domain/repositories/station.repsoitory"
import { CreateStationInput } from "../dtos/create-station.dto"
import { ICreateStationUseCase } from "../interfaces/station-usecases.interface"

export class CreateStationUseCase implements ICreateStationUseCase {
  constructor(private readonly stationRepository: IStationRepository) {}

  async execute(input: CreateStationInput): Promise<Station> {
    // Check if a station with the same name already exists
    const existingStation = await this.stationRepository.findByName(input.name)
    if (existingStation) {
      throw new AppError("Station with this name already exists", HTTP_STATUS.CONFLICT)
    }

    const station = new Station({
      id: "", // Will be generated by database/mapper
      ownerId: input.ownerId,
      name: input.name,
      description: input.description ?? "",
      contactPhone: input.contactPhone,
      contactEmail: input.contactEmail,
      location: {
        type: "Point",
        coordinates: [0, 0],
      },
      address: "",
      pincode: "",
      city: "",
      state: "",
      images: [],
      bays: 0,
      avgServiceTime: 0,
      operatingHours: [],
      holidays: [],
      amenities: [],
      rating: 0,
      reviewCount: 0,
      verifiedAt: null,
      rejectionReason: null,
      status: "DRAFT",
      isActive: false,
      createdAt: new Date(),
    })

    return this.stationRepository.save(station)
  }
}