
export const SUCCESS_MESSAGES = {
  LOGIN_SUCCESS: "Login successful",
  SIGNUP_SUCCESS: "User registered. Please check your email for the OTP.",
  VERIFICATION_SUCCESS: "Verification successful",
  GOOGLE_SIGNIN_SUCCESS: "Google Sign-In successful",
  TOKEN_REFRESH_SUCCESS: "Token refreshed successfully",
  ACCOUNT_SETUP_SUCCESS: "Account setup successful",
  USER_RETRIEVED_SUCCESS: "User retrieved successfully",
  USERS_RETRIEVED_SUCCESS: "Users retrieved successfully",
  USER_UPDATED_SUCCESS: "User updated successfully",
  LOGOUT_SUCCESS: "Logout successful",
  PASSWORD_RESET_OTP_SENT: "Password reset OTP sent to your email",
  PASSWORD_RESET_SUCCESS: "Password reset successful",
  OWNER_CREATED_SUCCESS: "Owner profile created successfully",
  OWNER_RETRIEVED_SUCCESS: "Owner profile retrieved successfully",
  OWNER_UPDATED_SUCCESS: "Owner profile updated successfully",
  CATEGORY_CREATED_SUCCESS: "Vehicle category created successfully",
  CATEGORY_RETRIEVED_SUCCESS: "Vehicle category retrieved successfully",
  CATEGORIES_RETRIEVED_SUCCESS: "Vehicle categories retrieved successfully",
  CATEGORY_UPDATED_SUCCESS: "Vehicle category updated successfully",
  CATEGORY_DELETED_SUCCESS: "Vehicle category deleted successfully",
  CLASS_CREATED_SUCCESS: "Vehicle class created successfully",
  CLASS_RETRIEVED_SUCCESS: "Vehicle class retrieved successfully",
  CLASSES_RETRIEVED_SUCCESS: "Vehicle classes retrieved successfully",
  CLASS_UPDATED_SUCCESS: "Vehicle class updated successfully",
  CLASS_DELETED_SUCCESS: "Vehicle class deleted successfully",
} as const
