export const BOOKING = {
  STATUS: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    CHECKED_IN: "CHECKED_IN",
    IN_SERVICE: "IN_SERVICE",
    SERVICE_COMPLETED: "SERVICE_COMPLETED",
    AWAITING_HANDOVER: "AWAITING_HANDOVER",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
    NO_SHOW: "NO_SHOW",
    STALLED: "STALLED",
  },
  SERVICE_TYPE: {
    HALF: "HALF",
    FULL: "FULL",
  },
} as const

export type BookingStatus = (typeof BOOKING.STATUS)[keyof typeof BOOKING.STATUS]

export type ServiceType = (typeof BOOKING.SERVICE_TYPE)[keyof typeof BOOKING.SERVICE_TYPE]