export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: "Invalid Credentials",
  ACCOUNT_BLOCKED: "Account Blocked",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  NOT_FOUND: "Resource not found",
  BAD_REQUEST: "Bad request",
  INTERNAL_SERVER_ERROR: "Internal server error",
  VALIDATION_ERROR: "Validation error",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  TOKEN_EXPIRED: "Token expired",
  INVALID_TOKEN: "Invalid token",
  INVALID_OR_EXPIRED_OTP: "Invalid or expired OTP",
  INVALID_OR_EXPIRED_CODE: "Invalid or expired verification code",
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_EXISTS: "User already exists",
  ACCOUNT_NOT_VERIFIED: "Account is not verified",
  NO_ACCOUNT_WITH_EMAIL: "No account found with this email address",
  SOCIAL_ACCOUNT_PASSWORD_RESET: "Social login accounts cannot reset passwords",
  GOOGLE_TOKEN_REQUIRED: "Google token is required",
  GOOGLE_CONFIG_ERROR: "Google authentication client is not configured on the server",
  INVALID_GOOGLE_TOKEN_PAYLOAD: "Invalid Google token payload",
  GOOGLE_AUTH_FAILED: "Google authentication failed",
  GOOGLE_PROFILE_FETCH_FAILED: "Failed to fetch user profile from Google",
  INVALID_GOOGLE_ACCESS_TOKEN: "Invalid Google access token payload",
  INVALID_ROLE: "Invalid role specified",
  ROLE_UPDATE_FAILED: "Failed to update account role",
  REFRESH_TOKEN_REQUIRED: "Refresh token is required",
  INVALID_OR_EXPIRED_REFRESH_TOKEN: "Invalid or expired refresh token",
  USER_ID_REQUIRED: "User ID is required",
  OWNER_ALREADY_EXISTS: "Owner profile already exists for this user",
  OWNER_NOT_FOUND: "Owner profile not found",
} as const
