export const API_ROUTES = {
  BASE: "/api",
  AUTH: {
    ME: "/me",
    ROOT: "/api/auth",
    SIGNUP: "/signup",
    LOGIN: "/login",
    VERIFY_OTP: "/verify-otp",
    GOOGLE: "/google",
    REFRESH_TOKEN: "/refresh-token",
    LOGOUT: "/logout",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    RESEND_OTP: "/resend-otp",
  },
  USERS: {
    ROOT: "/api/users",
    GET_ALL: "/",
    BOOKMARKS: "/bookmarks",
    TOGGLE_BOOKMARK: "/bookmarks/toggle",
    EXPORT: "/export",
    GET_BY_ID: "/:id",
    UPDATE: "/:id",
  },
  OWNER: {
    ROOT: "/api/owner",
    CREATE: "/",
    GET_PROFILE: "/me",
    UPDATE_PROFILE: "/me",
    ONBOARDING_STATUS: "/onboarding/status",
    ONBOARDING_STEP: "/onboarding/step",
    ONBOARDING_SUBMIT: "/onboarding/submit",
  },
  VEHICLE_CATALOG: {
    ROOT: "/api/vehicle-catalog",
    CATEGORIES: "/categories",
    CATEGORY_BY_ID: "/categories/:id",
    CLASSES: "/classes",
    CLASS_BY_ID: "/classes/:id",
  },
  STATIONS: {
    ROOT: "/api/stations",
    LIST: "/",
    CREATE: "/",
    BY_ID: "/:stationId",
    FILTER_OPTIONS: "/filter-options",
    SUBMIT: "/:stationId/submit",
    TOGGLE_ACTIVE: "/:stationId/toggle-active",
    ASSIGN_MANAGER: "/:stationId/assign-manager",
    REVIEW: "/:stationId/review",
  },
  VEHICLES: {
    ROOT: "/api/vehicles",
    LIST: "/",
    CREATE: "/",
    BY_ID: "/:id",
    SET_PRIMARY: "/:id/primary",
  },
  MANAGERS: {
    ROOT: "/api/managers",
    VERIFY_INVITATION: "/invitations/verify",
    ACCEPT_INVITATION: "/invitations/accept",
    REJECT_INVITATION: "/invitations/reject",
    INVITE: "/invite",
    LIST: "/",
    LIST_INVITATIONS: "/invitations",
    UPDATE_PERMISSIONS: "/:assignmentId/permissions",
    SUSPEND: "/:assignmentId/suspend",
    REACTIVATE: "/:assignmentId/reactivate",
    REMOVE: "/:assignmentId",
    RESEND_INVITATION: "/invitations/:invitationId/resend",
    CANCEL_INVITATION: "/invitations/:invitationId",
  },
} as const
