export const API_ROUTES = {
  BASE: "/api",
  AUTH: {
    ROOT: "/api/auth",
    SIGNUP: "/signup",
    LOGIN: "/login",
    VERIFY_OTP: "/verify-otp",
    GOOGLE: "/google",
    REFRESH_TOKEN: "/refresh-token",
    ME: "/me",
    LOGOUT: "/logout",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  USERS: {
    ROOT: "/api/users",
    GET_ALL: "/",
    GET_BY_ID: "/:id",
    UPDATE: "/:id",
  },
  OWNER: {
    ROOT: "/api/owner",
    CREATE: "/",
    GET_PROFILE: "/me",
    UPDATE_PROFILE: "/me",
    ONBOARDING_STATUS: "/onboarding/status",
    ONBOARDING_STEP: "/onboarding/step",
    ONBOARDING_SUBMIT: "/onboarding/submit",
  },
} as const
