export const API_ROUTES = {
  AUTH: {
    LOGIN: "/auth/login",
    GOOGLE: "/auth/google",
    SIGNUP: "/auth/signup",
    VERIFY_OTP: "/auth/verify-otp",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    CHANGE_PASSWORD: "/auth/change-password",
    REFRESH_TOKEN: "/auth/refresh-token",
    RESEND_OTP: "/auth/resend-otp",
  },
  USERS: {
    ROOT: "/users",
    BOOKMARKS: "/users/bookmarks",
    TOGGLE_BOOKMARK: "/users/bookmarks/toggle",
    EXPORT: "/users/export",
    BY_ID: (id: string) => `/users/${id}`,
  },
  STATIONS: {
    ROOT: "/stations",
    BY_ID: (id: string) => `/stations/${id}`,
    SUBMIT: (id: string) => `/stations/${id}/submit`,
    REVIEW: (id: string) => `/stations/${id}/review`,
    ASSIGN_MANAGER: (id: string) => `/stations/${id}/assign-manager`,
  },
  VEHICLES: {
    ROOT: "/vehicles",
    BY_ID: (id: string) => `/vehicles/${id}`,
    PRIMARY: (id: string) => `/vehicles/${id}/primary`,
  },
  BOOKINGS: {
    ROOT: "/bookings",
    BY_ID: (id: string) => `/bookings/${id}`,
    CANCEL: (id: string) => `/bookings/${id}/cancel`,
    WALK_IN: "/bookings/walk-in",
    CHECK_IN: "/bookings/check-in",
    UPDATE_STATUS: (id: string) => `/bookings/${id}/status`,
    UPCOMING: "/bookings/upcoming",
    HISTORY: "/bookings/history",
  },
  PAYMENT: {
    ROOT:'/payment',
    CREATE_ORDER: "/payment/create-order",
    VERIFY_PAYMENT: "/payment/verify-payment",
  },
  WALLET: {
    BALANCE: "/wallet",
    TRANSACTIONS: "/wallet/transactions",
    EXPORT: "/wallet/export",
    TOPUP_ORDER: "/wallet/topup/order",
    TOPUP_VERIFY: "/wallet/topup/verify",
    PAY: "/wallet/pay",
  },
} as const
