export const APP_ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  BOOKMARKS: "/bookmarks",
  AUTH: {
    LOGIN: "/login",
    SIGNUP: "/signup",
    VERIFY_EMAIL: "/verify-email",
    SETUP_ACCOUNT: "/setup-account",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    ACCEPT_INVITATION: "/accept-invitation",
  },
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    USER_DETAILS: (id: string | number) => `/admin/users/${id}`,
    OWNERS: "/admin/owners",
    STATIONS: "/admin/stations",
    STATION_DETAILS: (id: string | number) => `/admin/stations/${id}`,
    CATEGORIES: "/admin/categories",
    BOOKINGS: "/admin/bookings",
    QUEUES: "/admin/queues",
    REVIEWS: "/admin/reviews",
    FRAUD: "/admin/fraud",
    NOTIFICATIONS: "/admin/notifications",
    REPORTS: "/admin/reports",
    SETTINGS: "/admin/settings",
  },
  MANAGER: {
    ROOT: "/manager",
    DASHBOARD: "/manager/dashboard",
    QUEUE: "/manager/queue",
    QUEUES: "/manager/queues",
    CHECK_IN: "/manager/check-in",
    WALK_INS: "/manager/walk-ins",
    STATION: "/manager/station",
    STATION_DETAILS: (id: string | number) => `/manager/station/${id}`,
  },
  OWNER: {
    ROOT: "/owner",
    DASHBOARD: "/owner/dashboard",
    QUEUES: "/owner/queues",
    BOOKINGS: "/owner/bookings",
    STATIONS: "/owner/stations",
    FINANCIAL_RECORDS: "/owner/financial-records",
    ANALYTICS: "/owner/analytics",
    FEEDBACK: "/owner/feedback",
    NOTIFICATIONS: "/owner/notifications",
    ONBOARDING: "/owner/onboarding",
  },
  VEHICLES: {
    DETAILS: (id: string | number) => `/vehicles/${id}`,
  },
  PROFILE: "/profile",
  WALLET: "/wallet",
} as const
