export const SOCKET_EVENTS = {
  // Client -> Server Room Subscriptions
  JOIN_USER: "join_user",
  LEAVE_USER: "leave_user",
  JOIN_STATION: "join_station",
  LEAVE_STATION: "leave_station",
  JOIN_BOOKING: "join_booking",

  // Real-Time System & User Events
  NOTIFICATION_RECEIVED: "NOTIFICATION_RECEIVED",
  QUEUE_UPDATED: "QUEUE_UPDATED",
  QUEUE_POSITION_CHANGED: "QUEUE_POSITION_CHANGED",
  PAYMENT_UPDATED: "PAYMENT_UPDATED",
  REFUND_PROCESSED: "REFUND_PROCESSED",
  REFUND_COMPLETED: "REFUND_COMPLETED",
  WALLET_UPDATED: "WALLET_UPDATED",

  // Booking & Queue Lifecycle Events
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_RESCHEDULED: "BOOKING_RESCHEDULED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  BOOKING_NO_SHOW: "BOOKING_NO_SHOW",
  BOOKING_CHECKED_IN: "BOOKING_CHECKED_IN",
  CHECKIN_SUCCESS: "CHECKIN_SUCCESS",
  CUSTOMER_CHECKED_IN: "CUSTOMER_CHECKED_IN",
  SERVICE_STARTED: "SERVICE_STARTED",
  WASH_STARTED: "WASH_STARTED",
  SERVICE_COMPLETED: "SERVICE_COMPLETED",
  WASH_COMPLETED: "WASH_COMPLETED",
  SERVICE_STALLED: "SERVICE_STALLED",
  BOOKING_STALLED: "BOOKING_STALLED",
  SERVICE_RESUMED: "SERVICE_RESUMED",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  HANDOVER_READY: "HANDOVER_READY",
  HANDOVER_COMPLETED: "HANDOVER_COMPLETED",
  POST_INSPECTION_COMPLETED: "POST_INSPECTION_COMPLETED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",

  // Issue Management Real-Time Events
  ISSUE_UPDATED: "issue_updated",
  ISSUE_RESOLVED: "issue_resolved",
  ISSUE_CLOSED: "issue_closed",
  ISSUE_ESCALATED: "issue_escalated",
  ISSUE_ASSIGNED: "issue_assigned",
} as const

export type SocketEventType = (typeof SOCKET_EVENTS)[keyof typeof SOCKET_EVENTS]
